### ISSUE TITLE
Add a way to configure exa to add new custom icons or colors

### ISSUE THREAD

**Issue by r0b0ji** [ogham/exa#1031] opened 2022-02-15 22:23 UTC
There should be a .config way to configure some aspects of exa. For ex: adding a new icon for a custom filetype or change color, etc...

**Comment by B4rc1** [comment] 2022-02-23 13:05
Or in an environment Variable inspired by [`$LS_COLORS`](https://man7.org/linux/man-pages/man5/dir_colors.5.html) like [lf](https://github.com/gokcehan/lf/wiki/Icons) has.

My use case for this is that I use a pretty niece bitmap font with a lot of icons in the private unicode area. For example my `LF_ICONS` looks like this:
![image](https://user-images.githubusercontent.com/10383737/155323958-966f7011-f5ed-45f9-b31e-ba4f17f5ac0d.png)
(taken from my [nix configuration](https://codeberg.org/B4rc1/dotfiles/src/branch/master/modules/shell/lf.nix#L69))

**Comment by B4rc1** [comment] 2022-02-23 13:11
duplicate of: https://github.com/ogham/exa/issues/535

**Comment by ariasuni** [comment] 2022-03-18 15:29
Also duplicate of #511.

**Closed by ariasuni** 2022-03-18 15:29 UTC
Labels: X › duplicate
