### ISSUE TITLE
exa-linux-x86_64 binary does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by pletnes** [ogham/exa#255] opened 2017-08-07 06:16 UTC
Downloaded the `exa` version that's out today in precompiled binary format. Tried the following:

```
~ λ exa -l
exa: error while loading shared libraries: libhttp_parser.so.2.1: cannot open shared object file: No such file or directory
~ λ ldd $(which exa)
	linux-vdso.so.1 =>  (0x00007ffc6c3bb000)
	libhttp_parser.so.2.1 => not found
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2fc98a1000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2fc969c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2fc9494000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2fc9277000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2fc9060000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2fc8c96000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558606838000)
```

I was very surprised to see `exa` link against an HTTP parser library, that hardly seems necessary to run an `ls` replacement? Also, `exa` fails to run because of this.

**Comment by Carpetsmoker** [comment] 2017-08-07 06:20
I had the same issue, and I used GitHub's issue tracker's search feature to find my answer ;-)

https://github.com/ogham/exa/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20libhttp

**Comment by stan-qaz** [comment] 2017-08-07 06:35
Same for OpenSuse Leap 42.2

stan@hp-Stan:~/bin> exa-linux-x86_64
exa-linux-x86_64: error while loading shared libraries: libhttp_parser.so.2.1: cannot open shared object file: No such file or directory

Checked the fix above but it isn't something I want to have to remember to do on every install.

**Comment by pletnes** [comment] 2017-08-07 06:50
@Carpetsmoker thanks, I obviously searched poorly. Lesson learned.

@stan-qaz is right though, the fix is a bit weird and HTTP parsing seems unnecessary for an ls replacement.

**Comment by milonimrod** [comment] 2017-08-07 07:33
Same problem here

**Comment by thedarkfalcon** [comment] 2017-08-08 01:15
I had the same problem, and couldn't seem to install the library on my os (centos). I believe the library is required for the git functionality. I did manage to compile the code with the flag which disables that functionality (as below).

`cargo install --no-default-features --git https://github.com/ogham/exa`

**Comment by adamgiacomelli** [comment] 2017-08-08 07:22
Had the same problem on linux mint - fixed with `sudo apt-get install libhttp-parser2.1`

**Comment by MGPalmer** [comment] 2017-08-17 08:18
Yeah same issue here on Ubuntu 16.04.3 LTS

**Comment by ogham** [comment] 2017-08-20 18:58
See #194. Lots of people hit this one :(

It *was* caused by libgit2 accidentally bringing in a dependency on libhttp_parser. Because the exa development VM downloads Git which brings in this dependency, I didn't spot it sooner. Now, the VM downloads a patched version of libgit2-sys that doesn't bring in the dependency, so this should be fixed come the next version of exa (any day now, I promise)

**Closed by ogham** 2017-08-20 18:58 UTC
