### ISSUE TITLE
Crash on broken symbolic links in Git repositories

### ISSUE THREAD

**Issue by IngoHeimbach** [ogham/exa#623] opened 2020-01-13 14:11 UTC
Hey, thanks for this great ls replacement tool. :smile: 

In the latest version v0.9.0 exa can be crashed when invoked with the `--git` option in a directory with a broken symbolic link.

Example:

```bash
exa --git --long
```
produces
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: start_thread
  16: clone
[1]    8695 abort (core dumped)  RUST_BACKTRACE=1 exa --long --git
```

**Comment by jcrd** [comment] 2020-01-13 14:37
Duplicate of #526 and #558.

**Comment by IngoHeimbach** [comment] 2020-01-13 14:41
Ah sorry, didn't see that!

**Comment by ogham** [comment] 2020-01-19 17:18
#584 should take care of this!

**Closed by ogham** 2020-01-19 17:18 UTC
