### ISSUE TITLE
Quote special characters in the output

### ISSUE THREAD

**Issue by technic** [ogham/exa#1026] opened 2022-02-09 17:21 UTC
I suggest to quote special characters in the output.

The old unix ls does it like this:

```
$ ls
'~'  '\0'  '\abc'  'foo bar'  '~x'   x~
```

In exa we have the following
```
$ exa
\0  \abc  foo bar  x~  ~  ~x
```

With files containing spaces, like 'foo bar' the current output is complete nonsense.

### Details:
```
$ exa --version
exa - list files on the command-line
v0.10.1 [-git]
https://the.exa.website/
```

OS: Ubuntu 21.10

**Comment by ariasuni** [comment] 2022-03-17 20:16
Duplicate of #211.

**Closed by ariasuni** 2022-03-17 20:16 UTC
Labels: X › duplicate
