### ISSUE TITLE
build-script-build isn't part of the exa testsuite 

### ISSUE THREAD

**Issue by sylvestre** [ogham/exa#651] opened 2020-04-13 08:56 UTC
In Debian/Ubuntu, we build packages and then, once the deb packages have been uploaded, we also run the testsuite on the deb files generated.

Usually, it is going fine. However, for exa, it is failing because it cannot find _build-script-build_
https://ci.debian.net/data/autopkgtest/unstable/amd64/r/rust-exa/4951106/log.gz

it isn't clear to me what is build-script-build and how it should be rebuilt as part of this task?!

Log:
```
   Compiling exa v0.9.0 (/usr/share/cargo/registry/exa-0.9.0)
     Running `CARGO_PKG_HOMEPAGE='https://the.exa.website/' CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=9 LD_LIBRARY_PATH='/tmp/tmp.nj04OqOAvP/target/debug/deps:/usr/lib' CARGO_PKG_VERSION_PRE= CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION=0.9.0 CARGO_PKG_NAME=exa CARGO=/usr/bin/cargo CARGO_MANIFEST_DIR=/usr/share/cargo/registry/exa-0.9.0 CARGO_PKG_DESCRIPTION='A modern replacement for ls' CARGO_PKG_AUTHORS='Benjamin Sago <ogham@bsago.me>' CARGO_PKG_REPOSITORY='https://github.com/ogham/exa' rustc --crate-name build_script_build build.rs --color never --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=1a798427c42063fa -C extra-filename=-1a798427c42063fa --out-dir /tmp/tmp.nj04OqOAvP/target/debug/build/exa-1a798427c42063fa -C incremental=/tmp/tmp.nj04OqOAvP/target/debug/incremental -L dependency=/tmp/tmp.nj04OqOAvP/target/debug/deps --extern datetime=/tmp/tmp.nj04OqOAvP/target/debug/deps/libdatetime-84e45bb032b259d3.rlib`
     Running `/tmp/tmp.nj04OqOAvP/target/debug/build/exa-1a798427c42063fa/build-script-build`
[exa 0.9.0] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
[exa 0.9.0] stack backtrace:
[exa 0.9.0]    0: backtrace::backtrace::libunwind::trace
[exa 0.9.0]              at /usr/src/rustc-1.42.0/vendor/backtrace/src/backtrace/libunwind.rs:88
[exa 0.9.0]    1: backtrace::backtrace::trace_unsynchronized
[...]
[exa 0.9.0]   22: std::panicking::try
[exa 0.9.0]              at src/libstd/panicking.rs:281
[exa 0.9.0]   23: std::panic::catch_unwind
[exa 0.9.0]              at src/libstd/panic.rs:394
[exa 0.9.0]   24: std::rt::lang_start_internal
[exa 0.9.0]              at src/libstd/rt.rs:51
[exa 0.9.0]   25: std::rt::lang_start
[exa 0.9.0]              at /usr/src/rustc-1.42.0/src/libstd/rt.rs:67
[exa 0.9.0]   26: main
[exa 0.9.0]   27: __libc_start_main
[exa 0.9.0]   28: _start
[exa 0.9.0] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `exa v0.9.0 (/usr/share/cargo/registry/exa-0.9.0)`
```

Example of another rust binary (cbindgen) working:
https://ci.debian.net/packages/r/rust-cbindgen/

**Comment by ariasuni** [comment] 2021-01-13 23:51
I’ve no idea how to reproduce your issue. I can’t find any reference to something even remotely similar to `build-script-build`. It’s referring to line 23 of `build.rs` but there’s nothing file opened at that line.

Can you provide more details so that it’s easier to find the actual problem?

**Comment by ariasuni** [comment] 2021-04-14 15:57
Is this still happening with 0.10.1? I could try to build exa on a Debian or Ubuntu VM to see if I can understand where this is coming from.

**Comment by ariasuni** [comment] 2021-05-05 23:41
I had a problem that made the famous `build-script-build` reappear:

```
$ cargo flamegraph
   Compiling exa v0.10.1 (/home/ariasuni/projets/contrib/exa)
    Finished release [optimized + debuginfo] target(s) in 31.94s
several possible targets found: ["exa", "build-script-build"], please pass `--bin <binary>` or `--example <example>` to cargo flamegraph to choose one of them

$ cargo flamegraph --bin build-script-build
error: no bin target named `build-script-build`

WARNING: building without debuginfo. Enable symbol information by adding the following lines to Cargo.toml:

[profile.release]
debug = true

cargo build failed: None
```

So I investigated, and `cargo metadata` gives me this:
<details><summary><code>cargo metadata</code></summary>

```json
      "targets": [
        {
          "kind": [
            "bin"
          ],
          "crate_types": [
            "bin"
          ],
          "name": "exa",
          "src_path": "/home/ariasuni/projets/contrib/exa/src/main.rs",
          "edition": "2018",
          "doc": true,
          "doctest": false,
          "test": true
        },
        {
          "kind": [
            "custom-build"
          ],
          "crate_types": [
            "bin"
          ],
          "name": "build-script-build",
          "src_path": "/home/ariasuni/projets/contrib/exa/build.rs",
          "edition": "2018",
          "doc": false,
          "doctest": false,
          "test": false
        }
      ],
```
</details>

So `build-script-build` is simply the internal name cargo or rustc uses for the build script — I guess the last `build` is because the file itself is named `build.rs`.

I tried using `debcargo` on Debian, it worked but then trying to build the package failed because of unmet dependencies, and Debian hasn’t the correct version (in Buster at least). It probably shows that I understand nothing about Debian packaging and that I will need help to understand the problem.

In the end, I’ve still no idea what’s wrong. exa’s `Cargo.toml` is pretty standard, and its `build.rs` does nothing fancy — the only thing it does is creating an `$OUT_DIR/version_string.txt` file that will be read while building exa.

**Comment by ariasuni** [comment] 2022-03-17 19:52
I’m gonna close this since I received no answer, please re-open if the problem continues to happen.

**Closed by ariasuni** 2022-03-17 19:52 UTC
