### ISSUE TITLE
Support --quoting-style switch and QUOTING_STYLE env var

### ISSUE THREAD

**Issue by rpdelaney** [ogham/exa#467] opened 2019-01-14 17:51 UTC
from the GNU `ls` manpage:
```
--quoting-style=WORD
       use quoting style WORD for entry names: literal, locale, shell, shell-always, shell-
       escape, shell-escape-always, c, escape (overrides QUOTING_STYLE environment variable)
```
Based on my testing it seems that the default value is `shell-escape` but I didn't see that explicitly documented anywhere.

I don't know the difference between `shell-escape` vs `shell-escape-always`. You may not want to mirror the behavior of GNU `ls` perfectly here, though. Mainly it would be useful to me to be able to copy-paste and get a shell-parseable value.

**Comment by ogham** [comment] 2020-01-19 18:39
This would be a good thing to have.

**Comment by ariasuni** [comment] 2023-09-16 22:45
Duplicate of #216

**Closed by ariasuni** 2023-09-16 22:45 UTC
Labels: feature request
