### ISSUE TITLE
cargo install dies magnificently

### ISSUE THREAD

**Issue by pjobson** [ogham/exa#235] opened 2017-08-05 02:06 UTC
`cargo install --verbose --no-default-features --git https://github.com/ogham/exa`

All well and good until it tries to compile exa.

`Linux mediaserver 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

`cargo 0.16.0 (built 2017-03-13)`

      Compiling exa v0.7.0 (https://github.com/ogham/exa#ec472690)
         Running `rustc --crate-name exa /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs --crate-type lib -C opt-level=3 -C panic=abort -C metadata=2d3b18b71fd24f5c -C extra-filename=-2d3b18b71fd24f5c --out-dir /tmp/cargo-install.CQkRsjeZH0Sw/release/deps --emit=dep-info,link -L dependency=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps --extern natord=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libnatord-4816c1395272f395.rlib --extern unicode_width=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libunicode_width-21120d19e423c5c8.rlib --extern libc=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/liblibc-3511aa777c166228.rlib --extern lazy_static=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/liblazy_static-6a6022ba431e5adb.rlib --extern getopts=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libgetopts-d6e890c8a9410ee7.rlib --extern locale=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/liblocale-a05cecaab4aa521b.rlib --extern ansi_term=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libansi_term-617b1eacc6723c44.rlib --extern users=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libusers-517d91a7cc264b6b.rlib --extern num_cpus=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libnum_cpus-41112afbc12bdabe.rlib --extern term_grid=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libterm_grid-4a6c4202de78fcf4.rlib --extern number_prefix=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libnumber_prefix-a8d70d51be8dc478.rlib --extern datetime=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libdatetime-edfda19852b58156.rlib --extern glob=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libglob-85ec4636411b5424.rlib --extern zoneinfo_compiled=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libzoneinfo_compiled-07b6a353ff1f1cdf.rlib --extern scoped_threadpool=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libscoped_threadpool-6f3963d7c17761c5.rlib --cap-lints allow`
    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/dir.rs:45:18
       |
    45 |         Ok(Dir { contents, path, git })
       |                  ^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/dir.rs:45:28
       |
    45 |         Ok(Dir { contents, path, git })
       |                            ^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/dir.rs:45:34
       |
    45 |         Ok(Dir { contents, path, git })
       |                                  ^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/file.rs:69:19
       |
    69 |         Ok(File { path, parent_dir, metadata, ext, name })
       |                   ^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/file.rs:69:25
       |
    69 |         Ok(File { path, parent_dir, metadata, ext, name })
       |                         ^^^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/file.rs:69:37
       |
    69 |         Ok(File { path, parent_dir, metadata, ext, name })
       |                                     ^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/file.rs:69:47
       |
    69 |         Ok(File { path, parent_dir, metadata, ext, name })
       |                                               ^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/file.rs:69:52
       |
    69 |         Ok(File { path, parent_dir, metadata, ext, name })
       |                                                    ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/file.rs:202:53
        |
    202 |             FileTarget::Ok(File { parent_dir: None, path, ext, metadata, name })
        |                                                     ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/file.rs:202:59
        |
    202 |             FileTarget::Ok(File { parent_dir: None, path, ext, metadata, name })
        |                                                           ^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/file.rs:202:64
        |
    202 |             FileTarget::Ok(File { parent_dir: None, path, ext, metadata, name })
        |                                                                ^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/fs/file.rs:202:74
        |
    202 |             FileTarget::Ok(File { parent_dir: None, path, ext, metadata, name })
        |                                                                          ^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/dir_action.rs:92:29
       |
    92 |         Ok(RecurseOptions { tree, max_depth })
       |                             ^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/dir_action.rs:92:35
       |
    92 |         Ok(RecurseOptions { tree, max_depth })
       |                                   ^^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/view.rs:30:19
       |
    30 |         Ok(View { mode, colours, style })
       |                   ^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/view.rs:30:25
       |
    30 |         Ok(View { mode, colours, style })
       |                         ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/view.rs:30:34
       |
    30 |         Ok(View { mode, colours, style })
       |                                  ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/view.rs:301:28
        |
    301 |             Ok(TimeTypes { accessed, modified, created })
        |                            ^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/view.rs:301:38
        |
    301 |             Ok(TimeTypes { accessed, modified, created })
        |                                      ^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/view.rs:301:48
        |
    301 |             Ok(TimeTypes { accessed, modified, created })
        |                                                ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/view.rs:378:21
        |
    378 |         FileStyle { classify, exts }
        |                     ^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/view.rs:378:31
        |
    378 |         FileStyle { classify, exts }
        |                               ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/mod.rs:141:22
        |
    141 |         Ok(Options { dir_action, view, filter })
        |                      ^^^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/mod.rs:141:34
        |
    141 |         Ok(Options { dir_action, view, filter })
        |                                  ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/options/mod.rs:141:40
        |
    141 |         Ok(Options { dir_action, view, filter })
        |                                        ^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:217:37
        |
    217 |                     let egg = Egg { table_row, xattrs, errors, dir, file };
        |                                     ^^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:217:48
        |
    217 |                     let egg = Egg { table_row, xattrs, errors, dir, file };
        |                                                ^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:217:56
        |
    217 |                     let egg = Egg { table_row, xattrs, errors, dir, file };
        |                                                        ^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:217:64
        |
    217 |                     let egg = Egg { table_row, xattrs, errors, dir, file };
        |                                                                ^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:217:69
        |
    217 |                     let egg = Egg { table_row, xattrs, errors, dir, file };
        |                                                                     ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:294:28
        |
    294 |         Row { cells: None, name, tree }
        |                            ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:294:34
        |
    294 |         Row { cells: None, name, tree }
        |                                  ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:299:28
        |
    299 |         Row { cells: None, name, tree }
        |                            ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:299:34
        |
    299 |         Row { cells: None, name, tree }
        |                                  ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:303:35
        |
    303 |         Row { cells: Some(cells), name, tree }
        |                                   ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/details.rs:303:41
        |
    303 |         Row { cells: Some(cells), name, tree }
        |                                         ^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/file_name.rs:29:13
       |
    29 |             file, colours,
       |             ^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/file_name.rs:29:19
       |
    29 |             file, colours,
       |                   ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/table.rs:261:23
        |
    261 |         Environment { tz, numeric, users }
        |                       ^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/table.rs:261:27
        |
    261 |         Environment { tz, numeric, users }
        |                           ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/table.rs:261:36
        |
    261 |         Environment { tz, numeric, users }
        |                                    ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/table.rs:290:32
        |
    290 |         Table { columns: colz, colours, env: &options.env, widths, time_format: &options.time_format }
        |                                ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/table.rs:290:60
        |
    290 |         Table { columns: colz, colours, env: &options.env, widths, time_format: &options.time_format }
        |                                                            ^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/table.rs:302:15
        |
    302 |         Row { cells }
        |               ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/table.rs:310:15
        |
    310 |         Row { cells }
        |               ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/time.rs:77:25
       |
    77 |         DefaultFormat { current_year, locale, date_and_time, date_and_year }
       |                         ^^^^^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/time.rs:77:39
       |
    77 |         DefaultFormat { current_year, locale, date_and_time, date_and_year }
       |                                       ^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/time.rs:77:47
       |
    77 |         DefaultFormat { current_year, locale, date_and_time, date_and_year }
       |                                               ^^^^^^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/time.rs:77:62
       |
    77 |         DefaultFormat { current_year, locale, date_and_time, date_and_year }
       |                                                              ^^^^^^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/time.rs:161:21
        |
    161 |         ISOFormat { current_year }
        |                     ^^^^^^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/tree.rs:142:22
        |
    142 |         TreeParams { depth, last }
        |                      ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/tree.rs:142:29
        |
    142 |         TreeParams { depth, last }
        |                             ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/output/tree.rs:163:37
        |
    163 |         Iter { current_depth: self, inner }
        |                                     ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:63:19
       |
    63 |             Exa { options, writer, args }
       |                   ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:63:28
       |
    63 |             Exa { options, writer, args }
       |                            ^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
      --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:63:36
       |
    63 |             Exa { options, writer, args }
       |                                    ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:174:65
        |
    174 |                 Mode::Lines                  => lines::Render { files, colours, style }.render(self.writer),
        |                                                                 ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:174:72
        |
    174 |                 Mode::Lines                  => lines::Render { files, colours, style }.render(self.writer),
        |                                                                        ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:174:81
        |
    174 |                 Mode::Lines                  => lines::Render { files, colours, style }.render(self.writer),
        |                                                                                 ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:175:64
        |
    175 |                 Mode::Grid(ref opts)         => grid::Render { files, colours, style, opts }.render(self.writer),
        |                                                                ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:175:71
        |
    175 |                 Mode::Grid(ref opts)         => grid::Render { files, colours, style, opts }.render(self.writer),
        |                                                                       ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:175:80
        |
    175 |                 Mode::Grid(ref opts)         => grid::Render { files, colours, style, opts }.render(self.writer),
        |                                                                                ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:175:87
        |
    175 |                 Mode::Grid(ref opts)         => grid::Render { files, colours, style, opts }.render(self.writer),
        |                                                                                       ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:176:67
        |
    176 |                 Mode::Details(ref opts)      => details::Render { dir, files, colours, style, opts, filter: &self.options.filter, recurse: self.options.dir_action.recurse_options() }.render(self.writer),
        |                                                                   ^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:176:72
        |
    176 |                 Mode::Details(ref opts)      => details::Render { dir, files, colours, style, opts, filter: &self.options.filter, recurse: self.options.dir_action.recurse_options() }.render(self.writer),
        |                                                                        ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:176:79
        |
    176 |                 Mode::Details(ref opts)      => details::Render { dir, files, colours, style, opts, filter: &self.options.filter, recurse: self.options.dir_action.recurse_options() }.render(self.writer),
        |                                                                               ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:176:88
        |
    176 |                 Mode::Details(ref opts)      => details::Render { dir, files, colours, style, opts, filter: &self.options.filter, recurse: self.options.dir_action.recurse_options() }.render(self.writer),
        |                                                                                        ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:176:95
        |
    176 |                 Mode::Details(ref opts)      => details::Render { dir, files, colours, style, opts, filter: &self.options.filter, recurse: self.options.dir_action.recurse_options() }.render(self.writer),
        |                                                                                               ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:177:84
        |
    177 |                 Mode::GridDetails(ref grid, ref details) => grid_details::Render { dir, files, colours, style, grid, details, filter: &self.options.filter }.render(self.writer),
        |                                                                                    ^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:177:89
        |
    177 |                 Mode::GridDetails(ref grid, ref details) => grid_details::Render { dir, files, colours, style, grid, details, filter: &self.options.filter }.render(self.writer),
        |                                                                                         ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:177:96
        |
    177 |                 Mode::GridDetails(ref grid, ref details) => grid_details::Render { dir, files, colours, style, grid, details, filter: &self.options.filter }.render(self.writer),
        |                                                                                                ^^^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:177:105
        |
    177 |                 Mode::GridDetails(ref grid, ref details) => grid_details::Render { dir, files, colours, style, grid, details, filter: &self.options.filter }.render(self.writer),
        |                                                                                                         ^^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:177:112
        |
    177 |                 Mode::GridDetails(ref grid, ref details) => grid_details::Render { dir, files, colours, style, grid, details, filter: &self.options.filter }.render(self.writer),
        |                                                                                                                ^^^^

    error: struct field shorthands are unstable (see issue #37340)
       --> /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs:177:118
        |
    177 |                 Mode::GridDetails(ref grid, ref details) => grid_details::Render { dir, files, colours, style, grid, details, filter: &self.options.filter }.render(self.writer),
        |                                                                                                                      ^^^^^^^

    error: aborting due to 74 previous errors

    error: failed to compile `exa v0.7.0 (https://github.com/ogham/exa#ec472690)`, intermediate artifacts can be found at `/tmp/cargo-install.CQkRsjeZH0Sw`

    Caused by:
      Could not compile `exa`.

    Caused by:
      process didn't exit successfully: `rustc --crate-name exa /home/pjobson/.cargo/git/checkouts/exa-d551ef44a896dca9/ec47269/src/exa.rs --crate-type lib -C opt-level=3 -C panic=abort -C metadata=2d3b18b71fd24f5c -C extra-filename=-2d3b18b71fd24f5c --out-dir /tmp/cargo-install.CQkRsjeZH0Sw/release/deps --emit=dep-info,link -L dependency=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps --extern natord=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libnatord-4816c1395272f395.rlib --extern unicode_width=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libunicode_width-21120d19e423c5c8.rlib --extern libc=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/liblibc-3511aa777c166228.rlib --extern lazy_static=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/liblazy_static-6a6022ba431e5adb.rlib --extern getopts=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libgetopts-d6e890c8a9410ee7.rlib --extern locale=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/liblocale-a05cecaab4aa521b.rlib --extern ansi_term=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libansi_term-617b1eacc6723c44.rlib --extern users=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libusers-517d91a7cc264b6b.rlib --extern num_cpus=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libnum_cpus-41112afbc12bdabe.rlib --extern term_grid=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libterm_grid-4a6c4202de78fcf4.rlib --extern number_prefix=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libnumber_prefix-a8d70d51be8dc478.rlib --extern datetime=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libdatetime-edfda19852b58156.rlib --extern glob=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libglob-85ec4636411b5424.rlib --extern zoneinfo_compiled=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libzoneinfo_compiled-07b6a353ff1f1cdf.rlib --extern scoped_threadpool=/tmp/cargo-install.CQkRsjeZH0Sw/release/deps/libscoped_threadpool-6f3963d7c17761c5.rlib --cap-lints allow` (exit code: 101)

**Comment by hoodie** [comment] 2017-08-05 07:11
This seems to be a duplicate of #197

**Comment by ogham** [comment] 2017-08-05 09:52
Yeah, exa uses struct field shorthand a *lot*, and that feature was only added in Rust 1.17. Upgrading to a later version will fix it.

**Closed by ogham** 2017-08-05 09:52 UTC
