### ISSUE TITLE
Error 0599 when make install on Ubuntu 18.04 with rustc 1.32

### ISSUE THREAD

**Issue by montao** [ogham/exa#553] opened 2019-07-31 15:29 UTC
I get the following error msg:

```
developer@1604:~/proj$ git clone https://github.com/ogham/exa.git
Cloning into 'exa'...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 6470 (delta 45), reused 70 (delta 40), pack-reused 6372
Receiving objects: 100% (6470/6470), 3.15 MiB | 756.00 KiB/s, done.
Resolving deltas: 100% (4583/4583), done.
developer@1604:~/proj$ cd exa/
developer@1604:~/proj/exa$ make install
cargo build --release --no-default-features --features "default"
    Updating crates.io index
  Downloaded number_prefix v0.3.0
  Downloaded log v0.4.6
  Downloaded term_grid v0.1.7
  Downloaded glob v0.3.0
  Downloaded datetime v0.4.7
  Downloaded natord v1.0.9
  Downloaded lazy_static v1.3.0
  Downloaded locale v0.2.2
  Downloaded env_logger v0.6.1
  Downloaded git2 v0.9.1
  Downloaded ansi_term v0.12.0
  Downloaded zoneinfo_compiled v0.4.8
  Downloaded users v0.9.1
  Downloaded scoped_threadpool v0.1.9
  Downloaded term_size v0.3.1
  Downloaded byteorder v1.3.2
  Downloaded num_cpus v1.10.0
  Downloaded num-traits v0.1.43
  Downloaded url v1.7.2
  Downloaded iso8601 v0.1.1
  Downloaded libc v0.2.51
  Downloaded humantime v1.2.0
  Downloaded termcolor v1.0.4
  Downloaded cfg-if v0.1.7
  Downloaded nom v1.2.4
  Downloaded matches v0.1.8
  Downloaded quick-error v1.2.2
  Downloaded num-traits v0.2.6
  Downloaded idna v0.1.5
  Downloaded percent-encoding v1.0.1
  Downloaded pad v0.1.5
  Downloaded libgit2-sys v0.8.1
  Downloaded unicode-normalization v0.1.8
  Downloaded unicode-bidi v0.3.4
  Downloaded pkg-config v0.3.14
  Downloaded libz-sys v1.0.25
  Downloaded smallvec v0.6.9
  Downloaded regex v1.1.6
  Downloaded cc v1.0.35
  Downloaded thread_local v0.3.6
  Downloaded utf8-ranges v1.0.2
  Downloaded memchr v2.2.0
  Downloaded aho-corasick v0.7.3
  Downloaded regex-syntax v0.6.6
  Downloaded ucd-util v0.1.3
   Compiling libc v0.2.51
   Compiling num-traits v0.2.6
   Compiling memchr v2.2.0
   Compiling pkg-config v0.3.14
   Compiling cc v1.0.35
   Compiling nom v1.2.4
   Compiling matches v0.1.8
   Compiling unicode-width v0.1.5
   Compiling smallvec v0.6.9
   Compiling ucd-util v0.1.3
   Compiling regex v1.1.6
   Compiling byteorder v1.3.2
   Compiling lazy_static v1.3.0
   Compiling percent-encoding v1.0.1
   Compiling cfg-if v0.1.7
   Compiling quick-error v1.2.2
   Compiling utf8-ranges v1.0.2
   Compiling bitflags v1.0.4
   Compiling termcolor v1.0.4
   Compiling natord v1.0.9
   Compiling number_prefix v0.3.0
   Compiling ansi_term v0.12.0
   Compiling glob v0.3.0
   Compiling scoped_threadpool v0.1.9
   Compiling unicode-bidi v0.3.4
   Compiling pad v0.1.5
   Compiling iso8601 v0.1.1
   Compiling unicode-normalization v0.1.8
   Compiling regex-syntax v0.6.6
   Compiling term_grid v0.1.7
   Compiling thread_local v0.3.6
   Compiling log v0.4.6
   Compiling humantime v1.2.0
   Compiling libz-sys v1.0.25
   Compiling libgit2-sys v0.8.1
   Compiling locale v0.2.2
   Compiling atty v0.2.11
   Compiling term_size v0.3.1
   Compiling num_cpus v1.10.0
   Compiling users v0.9.1
   Compiling aho-corasick v0.7.3
   Compiling num-traits v0.1.43
   Compiling datetime v0.4.7
   Compiling exa v0.9.0 (/home/developer/proj/exa)
   Compiling idna v0.1.5
   Compiling zoneinfo_compiled v0.4.8
error[E0599]: no method named `copied` found for type `std::option::Option<&u8>` in the current scope
   --> /home/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/zoneinfo_compiled-0.4.8/src/lib.rs:131:49
    |
131 |         let std_flag = tz.standard_flags.get(i).copied().unwrap_or_default() != 0;
    |                                                 ^^^^^^

error[E0599]: no method named `copied` found for type `std::option::Option<&u8>` in the current scope
   --> /home/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/zoneinfo_compiled-0.4.8/src/lib.rs:132:44
    |
132 |         let gmt_flag = tz.gmt_flags.get(i).copied().unwrap_or_default() != 0;
    |                                            ^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `zoneinfo_compiled`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:21: recipe for target 'target/release/exa' failed
make: *** [target/release/exa] Error 101

```

Then I updated rustc from 1.32 to most recent, and it works:

```
developer@1604:~/proj/exa$ rustc --version
rustc 1.36.0 (a53f9df32 2019-07-03)
developer@1604:~/proj/exa$ make install
cargo build --release --no-default-features --features "default"
   Compiling libc v0.2.51
   Compiling num-traits v0.2.6
   Compiling memchr v2.2.0
   Compiling cc v1.0.35
   Compiling pkg-config v0.3.14
   Compiling smallvec v0.6.9
   Compiling matches v0.1.8
   Compiling unicode-width v0.1.5
   Compiling nom v1.2.4
   Compiling ucd-util v0.1.3
   Compiling regex v1.1.6
   Compiling lazy_static v1.3.0
   Compiling byteorder v1.3.2
   Compiling quick-error v1.2.2
   Compiling percent-encoding v1.0.1
   Compiling utf8-ranges v1.0.2
   Compiling cfg-if v0.1.7
   Compiling bitflags v1.0.4
   Compiling termcolor v1.0.4
   Compiling glob v0.3.0
   Compiling scoped_threadpool v0.1.9
   Compiling number_prefix v0.3.0
   Compiling natord v1.0.9
   Compiling ansi_term v0.12.0
   Compiling unicode-normalization v0.1.8
   Compiling unicode-bidi v0.3.4
   Compiling pad v0.1.5
   Compiling regex-syntax v0.6.6
   Compiling iso8601 v0.1.1
   Compiling term_grid v0.1.7
   Compiling thread_local v0.3.6
   Compiling humantime v1.2.0
   Compiling log v0.4.6
   Compiling libz-sys v1.0.25
   Compiling libgit2-sys v0.8.1
   Compiling idna v0.1.5
   Compiling locale v0.2.2
   Compiling atty v0.2.11
   Compiling num_cpus v1.10.0
   Compiling users v0.9.1
   Compiling term_size v0.3.1
   Compiling num-traits v0.1.43
   Compiling aho-corasick v0.7.3
   Compiling datetime v0.4.7
   Compiling exa v0.9.0 (/home/developer/proj/exa)
   Compiling zoneinfo_compiled v0.4.8
   Compiling url v1.7.2
   Compiling env_logger v0.6.1
   Compiling git2 v0.9.1
    Finished release [optimized] target(s) in 2m 01s

```

**Comment by rusty-snake** [comment] 2019-07-31 16:05
Duplicate of #530 and #534.

**Closed** 2019-08-23 10:41 UTC
