### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by johnalanwoods** [ogham/exa#780] opened 2020-12-31 23:12 UTC
Is there any plan to support Apple Silicon/ARM64?

**Comment by alexclst** [comment] 2021-01-01 05:29
I'm curious about this too, but more for when a version installable from Homebrew itself is released, as that is how I used to have this installed. For the time being I've copied the x86_64 version from a backup, but longterm want exa installed via Homebrew again.

**Comment by johnalanwoods** [comment] 2021-01-01 11:42
@alexclst homebrew for ARM64 is already working great. I only have one formula I need the intel version for, and that's Exa.

**Comment by alexclst** [comment] 2021-01-01 17:50
> @alexclst homebrew for ARM64 is already working great. I only have one formula I need the intel version for, and that's Exa.

Yeah, same here. Homebrew working fine, but Exa the one remaining formula.

**Comment by ariasuni** [comment] 2021-01-01 18:31
The extent of the issue is unclear to me. Is exa compiling fine on macOS ARM64? Do we need to do something in this repository regarding the Howebrew formula? I suppose this issue is also asking for a build on GitHub releases too; I’ve no idea how this works so I don’t know if it’s possible.

**Comment by sschlesier** [comment] 2021-01-01 21:35
After installing rust, libgit2, and make (all via Apple Silicon home-brew) I was able to compile exa from source no problem at all.

However the home-brew formula is not working.

I'm seeing

**Comment by ariasuni** [comment] 2021-01-01 23:31
I investigated. Support for aarch64-apple-darwin has been added in [Rust 1.49.0](https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html#64-bit-arm-macos-and-windows-reach-tier-2) released 2020-12-31. [The Homebrew formula](https://formulae.brew.sh/formula/exa#default) is still using Rust 1.48.0, but Homebrew [was already using Rust 1.49.0 beta instead of 1.48.0 for macOS ARM](https://github.com/Homebrew/homebrew-core/commit/467c93255f5abd4d6c9cb500b45ff4e9b67ea5fc).

It seems update to Rust stable 1.49.0 is ongoing at [Howebrew/homebrew-core#68089](https://github.com/Homebrew/homebrew-core/pull/68089); let’s see if that fixes the Homebrew problem or not.

**Comment by carlocab** [comment] 2021-01-02 18:50
Switching to  Rust 1.49 on its own doesn't seem to be enough to fix build failures for exa: https://github.com/Homebrew/homebrew-core/pull/68089#issuecomment-753508619

**Comment by johnalanwoods** [comment] 2021-01-02 19:08
So I was able to compile manually using Rust 1.49. I have a stable ARM exa binary on my M1 Mac. 

Is this then something to do with the build script in brew?

**Comment by carlocab** [comment] 2021-01-02 19:11
By compile manually, do you mean using `cargo install exa`?

Anyway, the explanation for why it doesn't work for `brew` is in the comment just after the one I linked. The formula passes `--locked` to cargo install (we don't like unversioned dependencies), and that seems to be causing the build failure.

**Comment by johnalanwoods** [comment] 2021-01-02 20:53
@carlocab got it. 

Yep that's what I meant. 

So this should resolve in time. And certainly when GHC becomes ARM64 compatible?

**Comment by johnalanwoods** [comment] 2021-01-05 14:50
cool thanks @carlocab  - looks like a simple fix.

cc: @ogham @ariasuni

**Comment by infa-jowoods** [comment] 2021-01-13 10:07
@ariasuni  - I see there hasn't been a release in over a year, is it likely that it will take a long time for a release with the updated cargo.lock file?

**Comment by carlocab** [comment] 2021-01-13 11:37
Does `brew install --HEAD exa` also not work for you, @johnalanwoods?

**Comment by johnalanwoods** [comment] 2021-01-13 11:58
@carlocab  - nah because GHC 8.8 fails as x86 only.

Also --HEAD wouldn't be updated unless manually removed and installed/reinstalled.

**Comment by carlocab** [comment] 2021-01-13 23:48
Yes, of course, I meant after removing the `pandoc` dependency + lines that build the manuals. Anyway, that said, let's see if pulling in a newer `Cargo.lock` file will help...

**Comment by carlocab** [comment] 2021-01-14 00:12
I've taken the latest `Cargo.lock` file and monkey-patched it into the stable release (https://github.com/Homebrew/homebrew-core/pull/68973). It seems to work, so I guess you might get your brewed `exa` reasonably soon.

**Comment by carlocab** [comment] 2021-01-14 15:41
Above PR has been merged. Though it would still be nice to see a proper new release of exa that actually supports Apple Silicon, rather than having to patch the latest stable release to get it.

**Comment by johnalanwoods** [comment] 2021-01-14 16:02
@carlocab - thanks you're a star 👍🏼

**Comment by johnalanwoods** [comment] 2021-01-14 16:05
@carlocab  - if/when exa does release a new update, will that then flow down via homebrew, or require a new update by someone on homebrew side to reverse the formula change?

**Comment by carlocab** [comment] 2021-01-14 23:36
Not sure what you mean. When there is a new version of exa, the Homebrew formula will be updated in the same way any other formula is updated. If the new version uses a new enough lock file, then the lock file patch can be removed.

**Comment by ariasuni** [comment] 2021-04-06 12:08
Since Homebrow is providing exa 0.10.0 for Apple Silicon, I believe this issue can be closed.
https://formulae.brew.sh/formula/exa#default

**Closed by ariasuni** 2021-04-06 12:08 UTC

**Comment by jritsema** [comment] 2022-01-13 15:44
Hello. I tried to install exa via [asdf](https://github.com/nyrst/asdf-exa) on an m1 and got the following error.

```
asdf install exa 0.10.1
* Downloading exa release 0.10.1...
curl: (22) The requested URL returned error: 404
asdf-exa: Could not download https://github.com/ogham/exa/releases/download/v0.10.1/exa-macos-armv7-v0.10.1.zip
asdf-exa: An error ocurred while installing exa 0.10.1.
```
It seems like if this project published a `exa-macos-armv7-v0.10.1.zip`, then the asdf install would start working.  Thoughts?

**Comment by dumindu** [comment] 2022-02-06 11:58
@ariasuni Please add native Apple Silicon target builds to releases as well. Thanks :)

**Comment by carlocab** [comment] 2022-02-06 12:14
If you're in a pinch...
```
curl -sL -H 'Authorization: Bearer QQ==' -o exa.tar.gz "$(curl -s https://formulae.brew.sh/api/bottle/exa.json | jq -j '.bottles.arm64_big_sur.url')"
```
