### ISSUE TITLE
os error 95 when running 'exa -l' in sshfs directory

### ISSUE THREAD

**Issue by msehnout** [ogham/exa#178] opened 2017-05-11 12:14 UTC
I have a directory mounted with sshfs and it looks like this when I run `exa -l`
```txt
~/m/test_dir $ exa -l
.rw-r--r--  380 tcpdump 20 Apr  9:10 tcpdump2017-04-20--09:10:08.pcap
                                     └── <Operation not supported (os error 95)>
.rw-r--r--  160 tcpdump 20 Apr  9:10 tcpdump2017-04-20--09:10:11.pcap
                                     └── <Operation not supported (os error 95)>
.rw-r--r--  324 tcpdump 20 Apr  9:10 tcpdump2017-04-20--09:10:14.pcap
                                     └── <Operation not supported (os error 95)>
.rw-r--r--  392 tcpdump 20 Apr  9:10 tcpdump2017-04-20--09:10:17.pcap
                                     └── <Operation not supported (os error 95)>
.rw-r--r--  380 tcpdump 20 Apr  9:29 tcpdump2017-04-20--09:29:52.pcap
                                     └── <Operation not supported (os error 95)>
.rw-r--r--   92 tcpdump 20 Apr  9:29 tcpdump2017-04-20--09:29:55.pcap
                                     └── <Operation not supported (os error 95)>

```

**Comment by kballard** [comment] 2017-06-08 18:44
As near as I can tell, errors like that should only be able to show up if you either show xattrs (with `-@`) or use a tree view (with `-T`). Are you actually using either of those flags?

**Comment by crdx** [comment] 2017-07-07 19:32
exa is not supported on Windows 95

**Comment by msehnout** [comment] 2017-07-10 07:26
@kballard No, I'm using just `-l` and it happens with the newest upstream release as well:
```
~/mnt $ exa --version
exa 0.7.0
```

@crdx Good to know, but not relevant :-D

**Comment by ogham** [comment] 2017-07-10 10:48
@msehnout Thanks for checking with the newest version — it has some changes to the tree code, and bugs that mysteriously disappear tend to mysteriously *re*-appear later, so in a way it's good that it's stuck around.

I figured it out, though! @kballard is correct in that it should only be showing errors in the tree if you've got `--tree` or `--extended` on. However, it currently tries to the extended attributes whether you asked for them or not, and only *displays* them if you passed in the option. This is why you're getting errors for something you haven't asked for (I'm guessing os error 95 is when you ask for extended attributes on a filesystem that doesn't support them) (Also, do not ask why the code is like this, I honestly have no idea what/if I was thinking)

**Comment by simonwiles** [comment] 2017-07-25 19:17
any update on this?  can the be fixed for the next version?

**Comment by gimerstedt** [comment] 2017-08-04 06:16
duplicate of #126

**Comment by kaushalmodi** [comment] 2017-08-04 15:51
I saw this on RHEL 6.6

![image](https://user-images.githubusercontent.com/3578197/28976282-44a26b4a-790b-11e7-921f-9cba81c223f7.png)

**Comment by kalashnikov** [comment] 2017-08-04 16:08
I saw this issue in RHEL 6.7 
Installed from source code with make. 
> rustc 1.18.0 (03fc9d622 2017-06-06)
> exa 0.7.0

The message shows on a folder with samba protocol or remote disk. Maybe that's the reason.

**Comment by satyenr** [comment] 2017-08-07 12:45
Is this issue being tracked here? Or in #126? Seems like the same issue to me.

Anyway, I am facing the same error while using exa 0.7.0 over NFS.

```shell
shell ~ % exa --version
exa 0.7.0
shell ~ % 
```

**Comment by ogham** [comment] 2017-08-07 13:30
Hello, and apologies to everyone hitting this issue. The v0.8.0 milestone is just over a week away but I still want to get this done by then.

The problem is extended attributes. It seems that, when the OS asks the filesystem for a file's extended attributes, remote filesystems don't respond with "no xattrs" but instead "error 95", which I'm assuming means "operation not supported" or something. if the `xattr` feature is switched on (and it is by default), exa will query each file to see if it has any xattrs, displays a `@` character in the permissions column if there is one, and then list the attribute keys and lengths under each file if the `--extended` option was passed in.

However. My comment earlier -- when I thought I'd cracked the nut -- claims the following:

> it currently tries to the extended attributes whether you asked for them or not, and only displays them if you passed in the option.

The problem is that there are two things going on here: showing that there are *any* attributes with the `@` character, and showing the attributes' names under the file. What's going on is that, even though the user hasn't specified `--extended`, it's still querying each file for whether it should display the `@`. And on a network filesystem, it's going to return the same error for every file!

I can think of several solutions, none of which are ideal:

1. Stop querying the xattrs of every file unless `--extended` was passed. If there's no system call being made, then no system call can fail! But this wouldn't let you see which files had attributes in the listing without also seeing their values.
2. Continue querying each file for extended attributes, but if there's an error, then ignore it and don't show the `@`. The error just ends up cluttering the output and obscuring the actual information.
3. Split the `--extended` option in two, one for showing the `@` character and another for showing the items, so you can choose how much xattr querying you want.

My favoured solution is 2, because the distinction between "no xattrs" and "xattrs unavailable" isn't a major one if you're not explicitly seeking them out, and if you are, then the `--extended` option would tell you why they're unavailable. I don't think it should be up to the user to know whether they want to see the `@`s or not; it should be something you can have on by default because it won't cause any problems. Besides, exa already does something similar when trying to `stat` a non-existent file pointed to by a symlink: it just highlights the link in red instead of putting an annoying error on the screen, because the error's

**Comment by kballard** [comment] 2017-08-07 18:49
2 definitely seems the way to go. I don't have a way to test right now but I'd wager that macOS's `ls` handles errors the same way (well, it may just ignore errors entirely for xattrs even if you ask for the xattr listing, I don't know, but the important point is it almost certainly ignores errors when determining if it should show the `+` in the permissions list).

**Closed** 2017-08-12 10:29 UTC
Labels: invalid output!

**Comment by kaushalmodi** [comment] 2017-08-12 16:42
I confirm the fix. Thanks!
