### ISSUE TITLE
quick time sorting options

### ISSUE THREAD

**Issue by vzaliva** [ogham/exa#974] opened 2021-10-29 18:15 UTC
Very often I quickly need to list all recently modified files. Usually, I just type `ls -ltr`. 
With exa, I need to type `exa -l -s time` which is much longer.
It would be nice to add shorter option to sort by time or at least allow to abbreviate "time" to just "t".

**Comment by ariasuni** [comment] 2021-12-05 17:14
Duplicate of https://github.com/ogham/exa/issues/519

**Closed by ariasuni** 2021-12-05 17:14 UTC
