### ISSUE TITLE
Installation fails on windows. 

### ISSUE THREAD

**Issue by ZeerDonker** [ogham/exa#630] opened 2020-01-31 13:28 UTC
Hi,

The users library appears to be a linux specfic library. Which of course doesn't compile on windows :P  .  

I am seeing winapi libraries as something that is being built, when trying to install. Is this a linux/mac specific tool or was it a more crossplatform one? 

https://docs.rs/users/0.9.1/users/
`   Compiling users v0.9.1
error[E0433]: failed to resolve: could not find `unix` in `os``

**Comment by BasixKOR** [comment] 2020-02-04 19:19
Maybe duplicate of #32 ?

**Comment by ZeerDonker** [comment] 2020-02-12 09:42
Hmm. 

Could the readme be updated, to say it currently will not compile on windows? 

(Together with pointing to that issue.)

**Comment by FranklinYu** [comment] 2020-02-12 19:22
It's actually mentioned on https://the.exa.website (see the FAQ section), but maybe it's worth mentioning in README as well...

**Comment by skyline75489** [comment] 2021-03-28 03:56
Hi guys. I'm having promising result with PR #820. Check it work if you're interested.

**Comment by ariasuni** [comment] 2021-07-14 13:03
Closing this in favor of this older issue: https://github.com/ogham/exa/issues/32 (I added the link to the PR in the first comment)

**Closed by ariasuni** 2021-07-14 13:03 UTC
