### ISSUE TITLE
feature request `--time-style=relative` or `--time-style=human`

### ISSUE THREAD

**Issue by maxandersen** [ogham/exa#692] opened 2020-06-29 07:47 UTC
I like exa, and was hoping it would provide one feature I always wanted in ls :)

Something like: `exa --time-style=human` and then show timestamp relatively to now:

```
.rw-r--r-- 7.3k max 1 min       build.gradle
.rw-r--r-- 2.9k max 2 months    CONTRIBUTING.adoc
.rw-r--r-- 5.4k max 1 hour      CONTRIBUTORS.md
.rw-r--r-- 1.2k max 3 years     devfile.yaml
```

precise style, `exa --time-style=precise-human`

```
.rw-r--r-- 7.3k max 1m 2s        build.gradle
.rw-r--r-- 2.9k max 2m 5d 3s     CONTRIBUTING.adoc
.rw-r--r-- 5.4k max 1h           CONTRIBUTORS.md
.rw-r--r-- 1.2k max 3y 3d 45s    devfile.yaml
```

**Comment by anthraxx** [comment] 2020-09-02 17:11
duplicate of #270

**Comment by ogham** [comment] 2020-10-21 14:08
Yes, I will track this in #270. Your first guess was correct: it will probably be `--time-style=relative`.

**Closed by ogham** 2020-10-21 14:08 UTC
