### ISSUE TITLE
0.9.0 release

### ISSUE THREAD

**Issue by ignatenkobrain** [ogham/exa#441] opened 2018-11-14 13:27 UTC
There was no release for last year and I'm wondering when will new release come?

Thanks!

**Comment by bemeurer** [comment] 2018-12-06 04:36
Please make a new release!

**Comment by ogham** [comment] 2018-12-06 20:53
Soon™

**Comment by ariasuni** [comment] 2018-12-16 05:55
Duplicate of #389

**Comment by ignatenkobrain** [comment] 2019-02-10 10:26
I would appreciate if it would contain #469 and #461

**Comment by ToonSpin** [comment] 2019-03-10 15:25
Hi @ogham, any update on the progress toward a new release? Your comment saying "soon(tm)" is three months old at this point. Is there a place where we can see what's blocking a new release?

**Comment by okias** [comment] 2019-03-24 21:46
ping @ogham

**Comment by lilyball** [comment] 2019-04-08 07:07
There's 4 open issues in the [v0.9.0 milestone](https://github.com/ogham/exa/milestone/7) which I'd assume is what's holding up the release.

**Comment by PhilsLab** [comment] 2019-06-09 14:24
ping @ogham has this project died?

**Comment by kpcyrd** [comment] 2019-07-14 16:18
+1, we currently need to apply a large number of patches to build exa because the crates we have in debian are too new.

**Comment by MaxMilton** [comment] 2019-07-14 21:28
Would be great to see a release so the recent fixes (e.g., https://github.com/ogham/exa/issues/517) can trickle down into distro package managers. The remaining issues in the [v0.9.0](https://github.com/ogham/exa/milestone/7) have been there for years and surely shouldn't hold up a release.

**Comment by ogham** [comment] 2019-07-15 03:26
I'm sorry this took so long, everyone. But v0.9.0 is now under Releases.

**Closed by ogham** 2019-07-15 03:26 UTC
